[package]
name = "bikeseat"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.4"
actix-web = "4"
actix-files = "0.6.2"
serde_yaml = "0.9.33"
serde = { version = "1.0.197", features = ["derive"] }
env_logger = "0.11.3"
